# Generated by Django 4.0.3 on 2022-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='title',
        ),
        migrations.AddField(
            model_name='availability',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
